vim.cmd.colorscheme("retrobox")
vim.api.nvim_set_hl(0, "Normal",     { ctermbg = "none" })
vim.api.nvim_set_hl(0, "SignColumn", { ctermbg = "none" })
vim.api.nvim_set_hl(0, "@variable",  { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "@constant",  { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "@module",    { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "@function",  { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Normal",     { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Operator",   { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Function",   { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Special",    { fg = "#ebdbb2" })
vim.api.nvim_set_hl(0, "Delimiter",  { fg = "#ebdbb2" })
