#!/bin/sh
if [ -n "$1" ]; then
    if [ -f "$1" ]; then
        nohup xdg-open "$1" >/dev/null 2>&1 &
        disown
    else
        echo "Unable to find file $1"
    fi
else
    selected_file=$(fd . $HOME -e pdf --exclude 'Telegram Desktop' | fzf)
    if [ -n "$selected_file" ]; then
        nohup xdg-open "$selected_file" >/dev/null 2>&1 &
        disown
    fi
fi
