#!/bin/sh

SEARCH_DIR="${1:-.}"
kitty zsh -c "
    selected_file=\$(fd -e pdf . '$SEARCH_DIR' | fzf)
    if [ -n \"\$selected_file\" ]; then
        nohup zathura \"\$selected_file\" >/dev/null 2>&1 &
        disown
        sleep 0.3
    fi
"
